services:
  web:
    build: apache
    ports:
      - 8080:80
    volumes:
      - ./apache/tarefa1.conf:/etc/apache2/sites-enabled/tarefa1.conf
      - ./buenas.lan:/opt/web/buenas.lan    
    networks:
      redeapache:
        aliases:
          - www.buenas.lan
          - buenas.lan
          - eq1.buenas.lan
        ipv4_address: 192.168.30.10
    develop:
      watch:
        - path: ./apache/test1.conf
          action: restart

  cliente:
    image: brunosct/debian12-cliente-firefox
    hostname: cliente
    networks:
      redeapache:
        ipv4_address: 192.168.30.11
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix

networks:
  redeapache:
    ipam:
      config:
        - subnet: 192.168.30.0/24